### ISSUE TITLE
Support for shell aliases

### ISSUE THREAD

**Issue by frantic** [hugows/hf#3]
I have a bunch of shell aliases defined in my `.zshrc`, would be nice to be able to use them as commands for `hf`. https://github.com/facebook/PathPicker/ supports this.

Currently having defined `alias ll='ls -lah'`, using `ll $FILES` as command results in `sh: ll: command not found`

**Comment by hugows** [comment]
I totally missed that. Unfortunately that seems rather complicated to implement, and also specific to the shell you're using. Just google "python exec  command alias" to see the problems.

**Comment by frantic** [comment]
Sure, totally understand.
